import { useState } from 'react'
import { Dialog, IconButton } from '@mui/material'
import CloseRounded from '@mui/icons-material/CloseRounded'
import ChevronLeftRounded from '@mui/icons-material/ChevronLeftRounded'
import ChevronRightRounded from '@mui/icons-material/ChevronRightRounded'
import { AnimatePresence, motion } from 'framer-motion'
import { wedding } from '../../config/wedding.config'
import { Reveal } from '../common/Reveal'
export function GallerySection(){const[active,setActive]=useState<number|null>(null);const images=wedding.images.gallery;const move=(step:number)=>setActive(current=>current===null?0:(current+step+images.length)%images.length);return <section className="immersive-gallery"><Reveal><p className="section-index">04 / Galería</p><h2>Instantes que<br/><em>guardamos para siempre</em></h2></Reveal><div className="gallery-composition">{images.map((image,i)=><motion.button key={image.label} className={`gallery-frame frame-${i}`} onClick={()=>setActive(i)} aria-label={`Abrir ${image.label}`} initial={{clipPath:'inset(100% 0 0 0)'}} whileInView={{clipPath:'inset(0% 0 0 0)'}} viewport={{once:true}} transition={{duration:.8,delay:i*.08}}>{image.src?<img src={image.src} alt={image.label} loading="lazy"/>:<span><b>Agregar fotografía</b><small>{image.label}<br/>images.gallery[{i}]</small></span>}</motion.button>)}</div><Dialog fullScreen open={active!==null} onClose={()=>setActive(null)} slotProps={{paper:{className:'gallery-modal'}}}><IconButton aria-label="Cerrar galería" onClick={()=>setActive(null)} className="modal-close"><CloseRounded/></IconButton><IconButton aria-label="Fotografía anterior" onClick={()=>move(-1)} className="modal-prev"><ChevronLeftRounded/></IconButton><AnimatePresence mode="wait">{active!==null&&<motion.div key={active} className="modal-image" initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} exit={{opacity:0}}>{images[active].src?<img src={images[active].src} alt={images[active].label}/>:<span>Agregar fotografía<br/><small>{images[active].label}</small></span>}</motion.div>}</AnimatePresence><IconButton aria-label="Fotografía siguiente" onClick={()=>move(1)} className="modal-next"><ChevronRightRounded/></IconButton></Dialog></section>}
