import { useState, type FormEvent } from 'react'
import { Button, CircularProgress, Dialog, DialogContent, FormControl, FormControlLabel, FormHelperText, FormLabel, MenuItem, Radio, RadioGroup, TextField } from '@mui/material'
import FavoriteRounded from '@mui/icons-material/FavoriteRounded'
import { wedding } from '../../config/wedding.config'
import { submitRsvp } from '../../services/rsvpService'
import type { RsvpData } from '../../types/wedding'
import { Reveal } from '../common/Reveal'
const initial:RsvpData={name:'',attendance:'yes',guests:0,dietary:'',message:''}
export function RsvpSection(){const [data,setData]=useState(initial);const [nameError,setNameError]=useState('');const [loading,setLoading]=useState(false);const [open,setOpen]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();if(data.name.trim().length<3){setNameError('Ingresá tu nombre y apellido');return}setNameError('');setLoading(true);await submitRsvp(data);setLoading(false);setOpen(true)};return <section className="rsvp-cinematic" id="rsvp"><div className="rsvp-lights"/><Reveal><p className="dark-index">06 / RSVP</p><h2>¿Nos acompañás<br/><em>en este día?</em></h2><p className="rsvp-lead">Confirmá antes del {wedding.rsvpDeadline}. Tu respuesta nos ayuda a preparar cada detalle.</p><form onSubmit={submit} noValidate><TextField label="Nombre y apellido" required fullWidth value={data.name} error={Boolean(nameError)} helperText={nameError} onChange={e=>setData({...data,name:e.target.value})}/><FormControl><FormLabel>¿Vas a acompañarnos?</FormLabel><RadioGroup value={data.attendance} onChange={e=>setData({...data,attendance:e.target.value as 'yes'|'no'})}><FormControlLabel value="yes" control={<Radio/>} label="Sí, asistiré"/><FormControlLabel value="no" control={<Radio/>} label="No podré asistir"/></RadioGroup></FormControl>{data.attendance==='yes'&&<TextField select label="Cantidad de acompañantes" fullWidth value={data.guests} onChange={e=>setData({...data,guests:Number(e.target.value)})}>{[0,1,2,3,4].map(n=><MenuItem key={n} value={n}>{n}</MenuItem>)}</TextField>}<TextField label="Restricciones alimentarias" fullWidth value={data.dietary} onChange={e=>setData({...data,dietary:e.target.value})}/><TextField label="Mensaje para los novios (opcional)" multiline minRows={3} fullWidth value={data.message} onChange={e=>setData({...data,message:e.target.value})}/><FormHelperText>Demostración: la respuesta queda solamente en este dispositivo.</FormHelperText><Button type="submit" variant="contained" disabled={loading}>{loading?<CircularProgress size={22} color="inherit"/>:'Enviar confirmación'}</Button></form></Reveal><Dialog open={open} onClose={()=>setOpen(false)}><DialogContent className="thanks"><div className="petal-burst">{Array.from({length:8},(_,i)=><i key={i}/>)}</div><FavoriteRounded/><h2>¡Gracias por responder!</h2><p>Tu respuesta de demostración quedó guardada en este dispositivo.</p><Button onClick={()=>setOpen(false)}>Cerrar</Button></DialogContent></Dialog></section>}
